estruturando a searchbar
HenryBilby/projeto-integrador-ios pull request #11
Opened 2021-10-27 13:10 UTC by sarafelix25

2021-10-27 15:43 UTC, HenryBilby requested changes
Olá Sara,
Percebo o seu esforço e acho que você está no caminho certo, fiz alguns comentários que achei pertinente.
Depois precisamos marcar uma chamada de vídeo, para refatorarmos algumas coisas, tais como:
- nomes de atributos, afim de ficar mais claro qual componente que estamos utilizamos;
- nomes de métodos;
- remover alguns métodos que não estão sendo utilizados no momento;

2021-10-27 15:43 UTC, HenryBilby commented on Minha_HQ_Preferida/Minha_HQ_Preferida/DetailViewController.swift
>          carregaInformacoesComic()
Seria interessante mantermos os nomes do métodos em inglês, neste caso acho que seria melhor loadComics(), o que você acha?

2021-10-27 15:43 UTC, HenryBilby commented on Minha_HQ_Preferida/Minha_HQ_Preferida/ComicCollectionViewController.swift
> +        selectComicViewModel.searchComics(searchText: searchText)
Logo após a linha selectComicViewModel.searchComics(searchText: searchText), inserir a linha abaixo:
selectComic.reloadData() para recarregar a lista da CollectionView após ela passar pelo filtro, ok?

2021-10-27 15:43 UTC, HenryBilby commented on Minha_HQ_Preferida/Minha_HQ_Preferida/Model/ServiceComic.swift
> -
Temos duas alternativas:
1a) Fazer uma nova request na API, com base neste parâmetro searchText, gerando a nova lista e retornando para a ViewModel; ou
2a) Fazer um filtro na lista da ViewModel com base no searchText, sendo desnecessário a implementação deste método aqui no Service;
Eu acho melhor a 2a alternativa, fica mais simples de manter o código, teremos menos requisições na API e consequentemente menos tempo despendido, proporcionando uma melhor experiência ao usuário.

2021-10-27 15:43 UTC, HenryBilby commented on Minha_HQ_Preferida/Minha_HQ_Preferida/ViewModel/ComicViewModel.swift
>      public func searchComics(searchText: String) {
Se optarmos pela 2a alternativa mencionada no comentário anterior, teríamos algo assim:

public func searchComics(searchText: String) {
      self.comicList = self.comicList.filter {comicElement in
      return comicElement.description.contains(searchText)
      }
}

2021-10-27 20:06 UTC, sarafelix25 commented on Minha_HQ_Preferida/Minha_HQ_Preferida/ComicCollectionViewController.swift
> +        selectComicViewModel.searchComics(searchText: searchText)
Ook, o Adriano me orientou a procurá-lo que você conseguiria me ajudar mais

2021-10-27 20:14 UTC, sarafelix25 commented on Minha_HQ_Preferida/Minha_HQ_Preferida/ViewModel/ComicViewModel.swift
>      public func searchComics(searchText: String) {
mas aqui n seria bom manter a service comics? essa linha digo serviceComic.searchComicList(searchText: searchText) { list in

2021-10-29 14:40 UTC, HenryBilby commented on Minha_HQ_Preferida/Minha_HQ_Preferida/ViewModel/ComicViewModel.swift
>      public func searchComics(searchText: String) {
Então Sara, acho bom fazermos uma chamada para eu ti explicar melhor o meu comentário:
Temos duas alternativas:
1a) Fazer uma nova request na API, com base neste parâmetro searchText, gerando a nova lista e retornando para a ViewModel; ou
2a) Fazer um filtro na lista da ViewModel com base no searchText, sendo desnecessário a implementação deste método aqui no Service;

2021-10-29 18:20 UTC, sarafelix25 commented on Minha_HQ_Preferida/Minha_HQ_Preferida/ViewModel/ComicViewModel.swift
>      public func searchComics(searchText: String) {
Respondi no slack

2021-11-08 21:28 UTC, closed without merging