Feature/ajustando estrela favoritos
HenryBilby/projeto-integrador-ios pull request #16
Opened 2021-11-13 12:48 UTC by sarafelix25

## What does this PR do
- Ajustes estrela favorita comic
- Implementação de funcionalidade da estrela favorita comic (clique, print ao ser clicada e a troca de cor - de branca para amarela)

2021-11-14 01:44 UTC, HenryBilby requested changes

2021-11-14 01:44 UTC, HenryBilby commented on Minha_HQ_Preferida/Minha_HQ_Preferida/View/DetailViewController.swift
> +        let tappedImage = tapGestureRecognizer.view as? UIImageView
Sara eu acho que este objeto tappedImage não está sendo utilizado, favor avaliar se é necessário a sua criação.

2021-11-14 01:44 UTC, HenryBilby commented on Minha_HQ_Preferida/Minha_HQ_Preferida/View/DetailViewController.swift
> +        print("A comic foi favoritada")
Após a estrela estar amarela, se eu clicar nela para ficar branca de novo, ela fica branca?

2021-11-17 10:09 UTC, sarafelix25 commented on Minha_HQ_Preferida/Minha_HQ_Preferida/View/DetailViewController.swift
> +        let tappedImage = tapGestureRecognizer.view as? UIImageView
Na verdade essa parte pelo tutorial que segui é um método, se excluo ele a parte acima não faz sentido(do #selector)

2021-11-17 10:10 UTC, sarafelix25 commented on Minha_HQ_Preferida/Minha_HQ_Preferida/View/DetailViewController.swift
> +        print("A comic foi favoritada")
Não kkkkk preciso ajustar isso, ainda não tive tempo de pesquisar

2021-11-17 12:46 UTC, sarafelix25 commented on Minha_HQ_Preferida/Minha_HQ_Preferida/View/DetailViewController.swift
> +        print("A comic foi favoritada")
Não kkkkk preciso ajustar isso, ainda não tive tempo de pesquisar

2021-11-17 12:48 UTC, HenryBilby commented on Minha_HQ_Preferida/Minha_HQ_Preferida/View/DetailViewController.swift
> +        let tappedImage = tapGestureRecognizer.view as? UIImageView
Certo Sara, então eu não me referia ao método 
"@objc func imageTapped(tapGestureRecognizer: UITapGestureRecognizer)" concordo que é fundamental que ele esteja aí.

Eu me refiro ao objeto tappedImage, me explica o que a linha abaixo está fazendo:
let tappedImage = tapGestureRecognizer.view as? UIImageView

Obs.: Meu objetivo com esta pergunta não é atrasar a sprint, eu acho mais importante que você entenda o que está fazendo e evolua como dev do que entregar algo no prazo. Estou junto com você nesta caminhada =)

2021-11-17 15:34 UTC, sarafelix25 commented on Minha_HQ_Preferida/Minha_HQ_Preferida/View/DetailViewController.swift
> +        let tappedImage = tapGestureRecognizer.view as? UIImageView
Aaah tá, é que no comentário puxou tudo, não a linha 40 só. Eu entendi que ele tá fazendo a ação do clique na estrelinha funcionar, reconhecendo o toque mesmo que seja uma imagem

2021-11-19 16:13 UTC, HenryBilby commented on Minha_HQ_Preferida/Minha_HQ_Preferida/View/DetailViewController.swift
> +        let tappedImage = tapGestureRecognizer.view as? UIImageView
Entendi, então Sara, esta linha:
let tappedImage = tapGestureRecognizer.view as? UIImageView

Está recuperando qual ImageView teve o evento de tapGestureRecognizer, é muito útil quando temos mais de uma ImageView "escutando" o evento de tapGestureRecognizer...

No seu caso, poderíamos fazer algo assim:
@objc func imageTapped(tapGestureRecognizer: UITapGestureRecognizer) {
       if let tappedImage = tapGestureRecognizer.view as? UIImageView, tappedImage == favoriteComic {
           if tappedImage.tintColor == .yellow {
              tappedImage.tintColor == .white 
           } else {
               tappedImage.tintColor == .yellow
           }
       }
}

2021-11-24 22:55 UTC, merged